### ISSUE TITLE
Code not available for the Add Remove and Modify 

### ISSUE THREAD

**Issue by VinayTShetty** [AnilDeshpande/RecycleListVeiwDemo#1]
Hi Code Tutor,
The most important concept in RecycleView that is add/Remove/replace that code is not available in the git hub link 
Video link:-https://www.youtube.com/watch?v=iFmZvgrc4i0&list=PLfuE3hOAeWhbmDA26ARjViSjTcOHSqpmT&index=7

can u please provide the link for the code..
The git hub link posted for that Video is different.

**Comment by AnilDeshpande** [comment]
As discussed in comment section with you, this was oversight by @VinayTShetty while reporting. Thanks for commenting . I am closing it.
